[versions]
compose = "1.4.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.10.1" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.1" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2023.06.01" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version = "1.7.2" }
compose-coil = { group = "io.coil-kt", name = "coil-compose", version = "2.4.0" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.1" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-paging = { group = "androidx.paging", name = "paging-compose", version = "3.2.0" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.6.1" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version = "2.44" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version = "2.44" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.0.0" }

test-androidx-core = { group = "androidx.test", name = "core", version = "1.5.0" }
test-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.7.3" }
test-junit = { group = "junit", name = "junit", version = "4.13.1" }
test-mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "4.1.0" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version = "2.9.0" }
retrofit-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "4.11.0" }

[plugins]
com-android-application = { id = "com.android.application", version = "8.0.2" }
com-android-library = { id = "com.android.library", version = "8.0.2" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.8.10" }

android-application = { id = "com.dbel.android.application", version = "1.0.0" }
android-application-compose = { id = "com.dbel.android.application.compose", version = "1.0.0" }

android-hilt = { id = "com.google.dagger.hilt.android", version = "2.44" }

android-library = { id = "com.dbel.android.library", version = "1.0.0" }
android-library-compose = { id = "com.dbel.android.library.compose", version = "1.0.0" }