name: Build showcase app
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
jobs:
  Build-Showcase-App:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: 35.0.0

      - name: Assemble app
        run: ./gradlew app-container:showcase:assembleDebug